<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wd</name>
   <tag></tag>
   <elementGuidId>772c3dff-cc1e-489e-a8dd-91db62ba634c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72c92ea4-55d4-4f52-b855-3601a7b81d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kw</value>
      <webElementGuid>457a7505-d204-401c-ba0f-430770c261ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wd</value>
      <webElementGuid>20038692-e5c1-4673-8607-af5c02468aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s_ipt</value>
      <webElementGuid>c8eabe8f-5b42-47de-9605-2e7fd8b56da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f2ff6886-75ca-4208-91db-941de31d9e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8bb4b355-c3c6-41a3-b5fc-a7bbdf0285e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kw&quot;)</value>
      <webElementGuid>46c2f28c-2aca-4d79-93c2-cb3e73812d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kw']</value>
      <webElementGuid>7ba8cabe-f26c-4226-86a3-219e23f7ede5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/span/input</value>
      <webElementGuid>69d16ab0-28b4-4ed3-8b27-13222278b026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>04d98088-6bc6-4763-b0da-10f5a925930d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kw' and @name = 'wd']</value>
      <webElementGuid>524cb93f-c061-4b06-a4b8-533880f1d851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
