<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>百度数据库</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8857997e-47cb-4cc0-9c20-71ba855d8b11</testSuiteGuid>
   <testCaseLink>
      <guid>28b4893c-e007-4448-9b9b-f468985be54f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/New Test Case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d41c6fb4-0bce-46cf-822d-745717c91976</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/100个网站数据库</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d41c6fb4-0bce-46cf-822d-745717c91976</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>bada35fe-ace1-4200-bcd0-10c2f74512c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d41c6fb4-0bce-46cf-822d-745717c91976</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>475dcbd6-e146-4477-94f0-06c9bdbb296f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
