<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__su</name>
   <tag></tag>
   <elementGuidId>4ee2754a-d06f-45c0-bb9a-fb1c08d47021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#su</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='su']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfce857e-c72b-4f5d-9bee-2ab2ca5e56ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>95080818-dc9b-4628-888c-1e9d42cc523b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>su</value>
      <webElementGuid>d86a0c3f-6d04-4719-aa10-37b4e0ca92f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>百度一下</value>
      <webElementGuid>8c1830ad-580b-4d26-aeab-cd5921cc554a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg s_btn btn_h btnhover</value>
      <webElementGuid>50f71c2f-ede4-4ba9-9792-0867849e4800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;su&quot;)</value>
      <webElementGuid>85c142c0-d293-4e59-af07-751dee9b6276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='su']</value>
      <webElementGuid>1825fbed-7d5f-44b6-bda5-16b90f4a7375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/span[2]/input</value>
      <webElementGuid>7b965abf-9a42-470b-bbb9-f3ef74b36e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>7c248004-8cf8-482d-bfe0-8b7d2712436d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'su']</value>
      <webElementGuid>8dd221d1-5fc6-4176-af3b-43c6deec1a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
