<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wd</name>
   <tag></tag>
   <elementGuidId>c28a1a08-6742-4272-9835-31f96f30fdc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f31431e7-fd5a-4bd6-82fc-d883ebcbb200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kw</value>
      <webElementGuid>4f813aeb-4752-4e5d-beb9-554a18a9004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wd</value>
      <webElementGuid>1dbe08c4-d03a-4d29-8897-00e03f65fba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s_ipt</value>
      <webElementGuid>a468bca1-22e7-4c80-a6cc-fa661a54f9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5b7e4c6f-f358-41b1-8958-80b3381bbb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d55b03c-d3e3-4435-bf04-db2e953a3890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kw&quot;)</value>
      <webElementGuid>173bc4f7-2abe-44c0-9959-82eb35269a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kw']</value>
      <webElementGuid>ca2caeb3-abe6-446f-afdf-bd11a1ee6aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/span/input</value>
      <webElementGuid>6ec2f13a-f0a7-4eb3-9d40-43d18489b5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>f231490f-9d25-48f3-bd65-671bc9caeb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kw' and @name = 'wd']</value>
      <webElementGuid>a3b9dcc2-20de-4134-b314-f1a150e59e79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
