<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__su</name>
   <tag></tag>
   <elementGuidId>f7de49ab-1d25-46e0-9eb7-f67276f3b39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#su</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='su']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78d74a8e-0d3f-4158-88aa-611efdd1d965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>139a5963-711a-44dc-a38e-4f86e382b29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>su</value>
      <webElementGuid>65201fb2-0481-40bd-9a95-512e02df6881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>百度一下</value>
      <webElementGuid>a94f28eb-719b-4e60-91a9-e5cc31124b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg s_btn btn_h btnhover</value>
      <webElementGuid>622262f8-7588-4949-9f9a-33a149bd581b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;su&quot;)</value>
      <webElementGuid>62417824-d666-4837-abb1-a2343e9ddbb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='su']</value>
      <webElementGuid>84f31375-8574-4855-9593-8e6ef910f784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/span[2]/input</value>
      <webElementGuid>c5773ea9-302c-4d43-b356-24e46220bcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>02d39576-b0f0-45f2-97d7-3ff199a38d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'su']</value>
      <webElementGuid>b0b2fca6-386e-485e-b04b-1c27c119a118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
